primousers/primostudio

features.json
Add-on that does something very cool!
=> Add this add-on

features.json
Reverts primousers/primostudio#3
=> Revert "hackathon trial"

features.json
Reverts primousers/primostudio#2
=> Revert "hackathon"

features.json
Reverts primousers/primostudio#1
reverting for primo studio demo
=> Revert "Add this add-on"

features.json
=> Add Report a bug add-on

features.json
Note: Please do not merge.
Current Status: Testing and validation.
=> Adds BrowZine Primo Studio addon.

features.json
=> New addon - primo-explore-filter-data-base-by-category-search

features.json
hi, don't know if it's ok...
i created a pull request, is there some errors? or conflicts?
=> updating an addon in primo studio - the title and version

features.json
- auto-reformat `features.json` to standardize indentation
- add ['primo-explore-unpaywall'](https://npmjs.com/package/primo-explore-unpaywall/) package description to `features.json`
- I'm more than happy to uncommit [`4e498a0`](https://github.com/primousers/primostudio/commit/4e498a096616e003488c5da5838da4322e8ce19b) (the whitespace changes), if desired.
- it's recommended to 'ignore whitespace' when looking at this PR
=> primo-explore-unpaywall: Add 'bulib-unpaywall' (with configuration) to primostudio

features.json
- add ['primo-explore-help-menu'](https://npmjs.com/package/primo-explore-help-menu/) package description to `features.json`
=> bulib-helpmenu: add 'primo-explore-help-menu'

features.json
sorry for all the turbulence and bother. 😅
=> bulib: remove 'primo-explore-help-menu', version bump 'primo-explore-unpaywall'

features.json
Tested in submit_here, addon appears in Primo Studio. @ajones3066 or @gloriousgeneralist, do either one of you two have an Unpaywall API key to test? We do not.
=> New addon - Unpaywall

features.json
Added wording to accommodate users looking for LibKey rather than BrowZine.
=> Branding Update to wording

features.json
@atla5 fyi
@ajones3066 please review
=> bulib: multiple version updates to 'help-menu' and 'unpaywall'

features.json
Adds LibKey Unpaywall integration options.
=> Adds LibKey Unpaywall integration options

features.json
fix multiple npmid for  primo-studio-browzine in master. 
@ajones3066 please review an approve this.  branch dev and submit_here are in sync currently.  after this is merged i would like indent features.json in all branches using jq.
=> sync multiple commits from dev to master

features.json
Hi! 👋 
We (Yewno) would like to add a new addon to Primo.  We followed the [Primo Studio Addon Tutorial](https://github.com/ExLibrisGroup/Primo-Studio-Addon-Tutorial) to create a new addon.  Please let us know if we packaged the addon incorrectly (we are new to the Primo ecosystem).
Thanks!
=> feat(new addon): add Yewno Primo Addon to features.json

features.json
Hi @gloriousgeneralist we'd like to submit an update to our previous addon originally submitted in PR #55.  Our updated addon supports more features, but otherwise is substantially similar to the previous submission.
=> feat(update addon): update yewno addon to v0.0.6

features.json
This is for the Yewno addition. It seemed to install, but I couldn't see any difference. Can anyone else see if this is actually working?
=> Submit here

features.json
update yewno primo addon to v0.0.6, using kebab-case hook
=> feat(update addon): update yewno addon to v0.0.6, w/ kebab hook

features.json
This includes some updates that Yewno has submitted. Needs a check on submit_here branch in Primo Studio.
=> verify Yewno edits in dev

features.json
=> Yewno fixes to master

features.json
Update yewno addon to version 0.0.8, using the correct primo hook
=> feat(yewno): addon 0.0.8
